# Generated by Django 5.2 on 2025-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(),
        ),
    ]
