# Generated by Django 5.2 on 2025-12-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oyun', 'verbose_name_plural': 'Oyunlar'},
        ),
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Oyun Resmi', 'verbose_name_plural': 'Oyun Resimleri'},
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(verbose_name='Kategori Resmi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Oyun Açıklaması'),
        ),
        migrations.AlterField(
            model_name='game',
            name='download_url',
            field=models.URLField(verbose_name='İndirme/Satın Alma Linki'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster_image',
            field=models.URLField(verbose_name='Poster Resmi'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Oyun Adı'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_url',
            field=models.URLField(verbose_name='Video URL (YouTube)'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image_url',
            field=models.URLField(verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Resim Açıklaması'),
        ),
    ]
